services:
  dev:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    volumes:
      - .:/workspace:cached
    env_file:
      - .env
    environment:
      - TNS_ADMIN=/workspace/wallet
    command: sleep infinity
  pgsql:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  pgdata:
